name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose --release -- --nocapture
    - name: Commit Generated Images
      env:
        # The GITHUB_TOKEN is automatically provided by GitHub Actions.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Configure git.
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

        # Stage your generated images.
        git add output/

        # Check if there are changes to commit.
        if ! git diff-index --quiet HEAD; then
          # Include "[skip ci]" in the commit message to prevent re-triggering the workflow.
          git commit -m "Update generated images [skip ci]"
          git push
        else
          echo "No changes detected, nothing to commit."
        fi
